### ISSUE TITLE
Dyno.deserialize doesn't like non-wire-format JSON

### ISSUE THREAD

**Issue by emilymcafee** [mapbox/dynamodb-migrator#5]
The change I made in https://github.com/mapbox/dynamodb-migrator/pull/3 (use Dyno.deserialize, expecting wire-format from a backup instead of line-deliminated JSON) doesn't play nice with feeding in a list of keys that look like `{ id: "foo", collection: "foo:bar"}`.

I think the migrator should continue support for line-deliminated JSON, especially in stream mode (i.e. for  "give me a list of keys to target, and I'll do stuff to them").  Maybe this should be an additional option passed only in stream mode, like a `--json` flag or something. Since I messed this up in the first place I can take this on, let me know what you think @rclark.

**Comment by rclark** [comment]
Yeah sounds good -- there's no way to auto-detect whether the file is coming at you in wire-format or objects, so the user would have to specify. Assume wire format, let the user flag it if they're dyno objects.

I cringe at calling one wire-format and the other JSON because they're both JSON. Got any better ideas though? I kinda don't.
